/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.pt.calculadora.frontend;

import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import br.com.pt.calculadora.backend.BackEnd_Code;

import javax.swing.JFrame;

import java.util.ArrayList;
import java.util.List;

public class FrontEndCode_View1 extends javax.swing.JFrame {    
        
        int On_Off =0;     // Armazena o valor de desligar ou ligar a interface da calculadora
        
        int Level_Op =0;   // Nivel da Operaçao
        
        double Numero_01;  // Armazena o primeiro conjunto da operaçao
        double Numero_02;  // Armazena o segundo conjunto da operaçao                
        
        String Operaçao;   // Tipo da operaçao, realizada
        
    
        FrontEndCode_View3 enviatexto; // Variavel de Envio para outra Tela
        
        BackEnd_Code kelps = new BackEnd_Code(); // Novo Objeto
    
    public FrontEndCode_View1() {
        initComponents();
        Txt_Lcd.setText("");
        Desativa_Botoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt_Lcd = new javax.swing.JTextField();
        Bt_DG_OnOff = new javax.swing.JButton();
        Bt_DG_CE = new javax.swing.JButton();
        Bt_Op_Soma = new javax.swing.JButton();
        Bt_Op_Subtracao = new javax.swing.JButton();
        Bt_Op_Multiplicacao = new javax.swing.JButton();
        Bt_Op_Divisao = new javax.swing.JButton();
        Bt_Op_Porcentagem = new javax.swing.JButton();
        Bt_Op_Raiz_Quadrada = new javax.swing.JButton();
        Bt_DG_00 = new javax.swing.JButton();
        Bt_DG_Ponto = new javax.swing.JButton();
        Bt_DG_01 = new javax.swing.JButton();
        Bt_DG_02 = new javax.swing.JButton();
        Bt_DG_03 = new javax.swing.JButton();
        Bt_DG_04 = new javax.swing.JButton();
        Bt_DG_05 = new javax.swing.JButton();
        Bt_DG_06 = new javax.swing.JButton();
        Bt_DG_07 = new javax.swing.JButton();
        Bt_DG_08 = new javax.swing.JButton();
        Bt_DG_09 = new javax.swing.JButton();
        Bt_Op_Igual = new javax.swing.JButton();
        Bt_Op_Potencializar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Txt_Sobre = new javax.swing.JMenu();
        Txt_Bt_Sobre = new javax.swing.JRadioButtonMenuItem();
        Txt_Op = new javax.swing.JMenu();
        Txt_Bt_Tela_Op = new javax.swing.JRadioButtonMenuItem();
        Txt_Sair = new javax.swing.JMenu();
        Txt_Bt_Sair = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Txt_Lcd.setEditable(false);
        Txt_Lcd.setBackground(new java.awt.Color(204, 255, 0));
        Txt_Lcd.setFont(new java.awt.Font("Cantarell", 1, 45)); // NOI18N
        Txt_Lcd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Bt_DG_OnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/On off.png"))); // NOI18N
        Bt_DG_OnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_OnOffActionPerformed(evt);
            }
        });

        Bt_DG_CE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/CE.png"))); // NOI18N
        Bt_DG_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_CEActionPerformed(evt);
            }
        });

        Bt_Op_Soma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Soma.png"))); // NOI18N
        Bt_Op_Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_SomaActionPerformed(evt);
            }
        });

        Bt_Op_Subtracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Subtração.png"))); // NOI18N
        Bt_Op_Subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_SubtracaoActionPerformed(evt);
            }
        });

        Bt_Op_Multiplicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Multiplicação.png"))); // NOI18N
        Bt_Op_Multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_MultiplicacaoActionPerformed(evt);
            }
        });

        Bt_Op_Divisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Divisão.png"))); // NOI18N
        Bt_Op_Divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_DivisaoActionPerformed(evt);
            }
        });

        Bt_Op_Porcentagem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_Op_Porcentagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Porcentagem.png"))); // NOI18N
        Bt_Op_Porcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_PorcentagemActionPerformed(evt);
            }
        });

        Bt_Op_Raiz_Quadrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bt_Op_Raiz_Quadrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Radiação.png"))); // NOI18N
        Bt_Op_Raiz_Quadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_Raiz_QuadradaActionPerformed(evt);
            }
        });

        Bt_DG_00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_00.jpg"))); // NOI18N
        Bt_DG_00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_00ActionPerformed(evt);
            }
        });

        Bt_DG_Ponto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bt_DG_Ponto.setText(".");
        Bt_DG_Ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_PontoActionPerformed(evt);
            }
        });

        Bt_DG_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_01.jpg"))); // NOI18N
        Bt_DG_01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_01ActionPerformed(evt);
            }
        });

        Bt_DG_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_02.jpg"))); // NOI18N
        Bt_DG_02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_02ActionPerformed(evt);
            }
        });

        Bt_DG_03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_03.jpg"))); // NOI18N
        Bt_DG_03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_03ActionPerformed(evt);
            }
        });

        Bt_DG_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_04.jpg"))); // NOI18N
        Bt_DG_04.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_04ActionPerformed(evt);
            }
        });

        Bt_DG_05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_05.jpg"))); // NOI18N
        Bt_DG_05.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_05ActionPerformed(evt);
            }
        });

        Bt_DG_06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_06.jpg"))); // NOI18N
        Bt_DG_06.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_06ActionPerformed(evt);
            }
        });

        Bt_DG_07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_07.jpg"))); // NOI18N
        Bt_DG_07.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_07ActionPerformed(evt);
            }
        });

        Bt_DG_08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_08.jpg"))); // NOI18N
        Bt_DG_08.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_08ActionPerformed(evt);
            }
        });

        Bt_DG_09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Numero_09.jpg"))); // NOI18N
        Bt_DG_09.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bt_DG_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DG_09ActionPerformed(evt);
            }
        });

        Bt_Op_Igual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bt_Op_Igual.setText("=");
        Bt_Op_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_IgualActionPerformed(evt);
            }
        });

        Bt_Op_Potencializar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/Potencializar.png"))); // NOI18N
        Bt_Op_Potencializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Op_PotencializarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Txt_Lcd))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bt_DG_OnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(Bt_DG_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(Bt_Op_Porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(Bt_Op_Raiz_Quadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bt_Op_Potencializar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bt_DG_07, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bt_DG_04, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Bt_DG_01, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Bt_DG_00, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bt_DG_02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Bt_DG_Ponto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bt_DG_08, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Bt_DG_05, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bt_DG_06, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(Bt_DG_09, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Bt_Op_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Bt_Op_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bt_DG_03, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bt_Op_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Bt_Op_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Bt_Op_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bt_DG_00, Bt_DG_01, Bt_DG_02, Bt_DG_03, Bt_DG_04, Bt_DG_05, Bt_DG_06, Bt_DG_07, Bt_DG_08, Bt_DG_09, Bt_Op_Igual});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bt_DG_CE, Bt_DG_OnOff, Bt_Op_Porcentagem, Bt_Op_Potencializar, Bt_Op_Raiz_Quadrada});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(Txt_Lcd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_Op_Potencializar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Op_Porcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(Bt_Op_Raiz_Quadrada, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(Bt_DG_OnOff))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Bt_Op_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bt_DG_08, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Bt_DG_07, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bt_DG_09, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bt_DG_06, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bt_DG_05, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Bt_DG_04, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Bt_Op_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_DG_03, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt_Op_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt_Op_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bt_DG_01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bt_DG_02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bt_DG_00, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Bt_DG_Ponto, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(Bt_Op_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bt_DG_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bt_DG_00, Bt_DG_01, Bt_DG_02, Bt_DG_03, Bt_DG_04, Bt_DG_05, Bt_DG_06, Bt_DG_Ponto, Bt_Op_Igual});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bt_DG_CE, Bt_DG_OnOff, Bt_Op_Porcentagem, Bt_Op_Potencializar, Bt_Op_Raiz_Quadrada});

        Txt_Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/about.png"))); // NOI18N
        Txt_Sobre.setText("Sobre");

        Txt_Bt_Sobre.setSelected(true);
        Txt_Bt_Sobre.setText("Sobre");
        Txt_Bt_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Bt_SobreActionPerformed(evt);
            }
        });
        Txt_Sobre.add(Txt_Bt_Sobre);

        jMenuBar1.add(Txt_Sobre);

        Txt_Op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/calculadora - Copia.png"))); // NOI18N
        Txt_Op.setText("Operaçoes");

        Txt_Bt_Tela_Op.setSelected(true);
        Txt_Bt_Tela_Op.setText("Ultimas Operaçoes");
        Txt_Bt_Tela_Op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Bt_Tela_OpActionPerformed(evt);
            }
        });
        Txt_Op.add(Txt_Bt_Tela_Op);

        jMenuBar1.add(Txt_Op);

        Txt_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pt/icones/saida.png"))); // NOI18N
        Txt_Sair.setText("Sair");
        Txt_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SairActionPerformed(evt);
            }
        });

        Txt_Bt_Sair.setSelected(true);
        Txt_Bt_Sair.setText("Sair");
        Txt_Bt_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Bt_SairActionPerformed(evt);
            }
        });
        Txt_Sair.add(Txt_Bt_Sair);

        jMenuBar1.add(Txt_Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ativa_Botoes(){
        Txt_Lcd.setEnabled(true);
        Bt_DG_CE.setEnabled(true);
        Bt_Op_Raiz_Quadrada.setEnabled(true);
        Bt_Op_Porcentagem.setEnabled(true);
        Bt_Op_Potencializar.setEnabled(true);
        Bt_Op_Divisao.setEnabled(true);
        Bt_Op_Multiplicacao.setEnabled(true);
        Bt_Op_Subtracao.setEnabled(true);
        Bt_Op_Soma.setEnabled(true);
        Bt_DG_00.setEnabled(true);
        Bt_DG_01.setEnabled(true);
        Bt_DG_02.setEnabled(true);
        Bt_DG_03.setEnabled(true);
        Bt_DG_04.setEnabled(true);
        Bt_DG_05.setEnabled(true);
        Bt_DG_06.setEnabled(true);
        Bt_DG_07.setEnabled(true);     
        Bt_DG_08.setEnabled(true); 
        Bt_DG_09.setEnabled(true); 
        Bt_DG_Ponto.setEnabled(true); 
        Bt_Op_Igual.setEnabled(true);        
    }
          
    private void Desativa_Botoes(){
        Txt_Lcd.setEnabled(false);
        Level_Op = 0;
        Bt_DG_CE.setEnabled(false);
        Bt_Op_Raiz_Quadrada.setEnabled(false);
        Bt_Op_Porcentagem.setEnabled(false);
        Bt_Op_Potencializar.setEnabled(false);
        Bt_Op_Divisao.setEnabled(false);
        Bt_Op_Multiplicacao.setEnabled(false);
        Bt_Op_Subtracao.setEnabled(false);
        Bt_Op_Soma.setEnabled(false);
        Bt_DG_00.setEnabled(false);
        Bt_DG_01.setEnabled(false);
        Bt_DG_02.setEnabled(false);
        Bt_DG_03.setEnabled(false);
        Bt_DG_04.setEnabled(false);
        Bt_DG_05.setEnabled(false);
        Bt_DG_06.setEnabled(false);
        Bt_DG_07.setEnabled(false);     
        Bt_DG_08.setEnabled(false); 
        Bt_DG_09.setEnabled(false); 
        Bt_DG_Ponto.setEnabled(false); 
        Bt_Op_Igual.setEnabled(false); 
    }    
    
    private void Limpa_Valores(){
        Numero_01 = 0;
        Numero_02 = 0;
        Txt_Lcd.setText("");
    }
    
    public void EnviaInfo(){
        
        if(Level_Op == 1){
                if (enviatexto == null){
                    enviatexto = new FrontEndCode_View3();
                    enviatexto.setVisible(false);

                    enviatexto.recebendo("1");
                }   
                else{
                    enviatexto.setVisible(false);
                    enviatexto.setState(FrontEndCode_View3.NORMAL);
                    
                    enviatexto.recebendo("1");
                }   
        }
        if(Level_Op == 2){
                if (enviatexto == null){
                    enviatexto = new FrontEndCode_View3();
                    enviatexto.setVisible(false);

                    enviatexto.recebendo("2");
                }   
                else{
                    enviatexto.setVisible(false);
                    enviatexto.setState(FrontEndCode_View3.NORMAL);
                    
                    enviatexto.recebendo("2");
                }   
        }
        if(Level_Op == 3){
                if (enviatexto == null){
                    enviatexto = new FrontEndCode_View3();
                    enviatexto.setVisible(false);

                    enviatexto.recebendo("3");
                }   
                else{
                    enviatexto.setVisible(false);
                    enviatexto.setState(FrontEndCode_View3.NORMAL);
                    
                    enviatexto.recebendo("3");
                }   
        } 
        if(Level_Op == 4){
                if (enviatexto == null){
                    enviatexto = new FrontEndCode_View3();
                    enviatexto.setVisible(false);

                    enviatexto.recebendo("4");
                }   
                else{
                    enviatexto.setVisible(false);
                    enviatexto.setState(FrontEndCode_View3.NORMAL);
                    
                    enviatexto.recebendo("4");
                }   
        }        
        if(Level_Op == 5){
                if (enviatexto == null){
                    enviatexto = new FrontEndCode_View3();
                    enviatexto.setVisible(false);

                    enviatexto.recebendo("5");
                }   
                else{
                    enviatexto.setVisible(false);
                    enviatexto.setState(FrontEndCode_View3.NORMAL);
                    
                    enviatexto.recebendo("5");
                }   
        }    
        
    }
    
    
    
    private void Bt_DG_OnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_OnOffActionPerformed
        // Liga os Botões da Calculadora
        if (On_Off == 0){
                Limpa_Valores();
                Ativa_Botoes();
                On_Off =1;
        }
        
        // Desliga os Botões da Calculadora
        else {  
                Limpa_Valores();
                Desativa_Botoes();
                On_Off =0;       
        }
    }//GEN-LAST:event_Bt_DG_OnOffActionPerformed

    private void Bt_DG_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_CEActionPerformed
        Limpa_Valores();
    }//GEN-LAST:event_Bt_DG_CEActionPerformed

    private void Bt_Op_SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_SomaActionPerformed
        Numero_01 = Double.parseDouble(Txt_Lcd.getText());               
        //#Copular o Objeto
        kelps.setNumero_01(Numero_01);
        //#Publicando no txt Area
        Txt_Lcd.setText("");       
        Operaçao = "Somar";
        Level_Op ++;
    }//GEN-LAST:event_Bt_Op_SomaActionPerformed

    private void Bt_Op_SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_SubtracaoActionPerformed
        
        if (Txt_Lcd.getText().equals("")){
            Txt_Lcd.setText("-");       
            Level_Op ++;
        }
        else {  
            Numero_01 = Double.parseDouble(Txt_Lcd.getText());                
            //#Copular o Objeto
            kelps.setNumero_01(Numero_01);
            //#Publicando no txt Area
            Txt_Lcd.setText("");        
            Operaçao = "Subtrair"; 
            Level_Op ++;
        }
    }//GEN-LAST:event_Bt_Op_SubtracaoActionPerformed

    private void Bt_Op_MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_MultiplicacaoActionPerformed
        Numero_01 = Double.parseDouble(Txt_Lcd.getText());               
        //#Copular o Objeto
        kelps.setNumero_01(Numero_01);
        //#Publicando no txt Area
        Txt_Lcd.setText("");        
        Operaçao = "Multiplicar";
        Level_Op ++;
    }//GEN-LAST:event_Bt_Op_MultiplicacaoActionPerformed

    private void Bt_Op_DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_DivisaoActionPerformed
        Numero_01 = Double.parseDouble(Txt_Lcd.getText());               
        //#Copular o Objeto
        kelps.setNumero_01(Numero_01);
        //#Publicando no txt Area
        Txt_Lcd.setText("");        
        Operaçao = "Dividir";  
        Level_Op ++;
    }//GEN-LAST:event_Bt_Op_DivisaoActionPerformed

    private void Bt_Op_PorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_PorcentagemActionPerformed
        Numero_02 = Double.parseDouble(Txt_Lcd.getText());             
        //#Copular o Objeto        
        if(Operaçao=="Somar"){
            kelps.setNumero_02(Numero_01+Numero_02*(Numero_01/100));
            Operaçao = "Porcento";
        }
        if(Operaçao=="Subtrair"){
            kelps.setNumero_02(Numero_01-Numero_02*(Numero_01/100));
            Operaçao = "Porcento";
        }
        if(Operaçao=="Multiplicar"){
            kelps.setNumero_02(Numero_02*(Numero_01/100)); 
            Operaçao = "Porcento";
        }    
    }//GEN-LAST:event_Bt_Op_PorcentagemActionPerformed

    private void Bt_Op_Raiz_QuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_Raiz_QuadradaActionPerformed
        if (Txt_Lcd.getText().equals("")){
            Operaçao = "Raiz";
            Level_Op ++;
        }
        else{
            Numero_01 = Double.parseDouble(Txt_Lcd.getText());               
            //#Copular o Objeto
            kelps.setNumero_01(Numero_01);
            //#Publicando no txt Area
            Txt_Lcd.setText("");        
            Operaçao = "Radiar";
            Level_Op ++;
        }
    }//GEN-LAST:event_Bt_Op_Raiz_QuadradaActionPerformed

    private void Bt_DG_PontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_PontoActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+".");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_PontoActionPerformed

    private void Bt_DG_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_00ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"0");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_00ActionPerformed

    private void Bt_DG_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_01ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"1");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_01ActionPerformed

    private void Bt_DG_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_02ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"2");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_02ActionPerformed

    private void Bt_DG_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_03ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"3");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_03ActionPerformed

    private void Bt_DG_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_04ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"4");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_04ActionPerformed

    private void Bt_DG_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_05ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"5");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_05ActionPerformed

    private void Bt_DG_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_06ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"6");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_06ActionPerformed

    private void Bt_DG_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_07ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"7");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_07ActionPerformed

    private void Bt_DG_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_08ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"8");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_08ActionPerformed

    private void Bt_DG_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DG_09ActionPerformed
        Txt_Lcd.setText(Txt_Lcd.getText()+"9");
        Txt_Lcd .setHorizontalAlignment(Txt_Lcd.CENTER);
    }//GEN-LAST:event_Bt_DG_09ActionPerformed

    private void Bt_Op_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_IgualActionPerformed
        
           switch(Operaçao){
               
            case "Porcento":
                String saida = "";
                saida += kelps.getNumero_02();
                Txt_Lcd.setText(saida);
                EnviaInfo();
                break;
               
            case "Somar":
                Numero_02 = Double.parseDouble(Txt_Lcd.getText());            
                //#Copular o Objeto
                kelps.setNumero_02(Numero_02);
                //#Publicando no txt Area
                saida = "";                                                                            
                saida += kelps.OpSomar() ;       
                Txt_Lcd.setText(saida);
                EnviaInfo();
                break;
                
            case "Subtrair":    
                Numero_02 = Double.parseDouble(Txt_Lcd.getText());            
                //#Copular o Objeto
                kelps.setNumero_02(Numero_02);
                //#Publicando no txt Area
                saida = "";                                                                            
                saida += kelps.OpSuntrair() ;       
                Txt_Lcd.setText(saida); 
                EnviaInfo();
                break;
            
            case "Multiplicar":    
                Numero_02 = Double.parseDouble(Txt_Lcd.getText());             
                //#Copular o Objeto
                kelps.setNumero_02(Numero_02);
                //#Publicando no txt Area
                saida = "";                                                                            
                saida += kelps.OpMultiplicar() ;       
                Txt_Lcd.setText(saida);
                EnviaInfo();
                break;  
                
            case "Dividir":
                try{
                    Numero_02 = Double.parseDouble(Txt_Lcd.getText());             
                    //#Copular o Objeto
                    kelps.setNumero_02(Numero_02);
                    //#Publicando no txt Area
                    saida = "";                                                                            
                    saida += kelps.OpDividir(Numero_01);       
                    Txt_Lcd.setText(saida);
                    EnviaInfo();
                }
                catch(Exception erro){
                    JOptionPane.showMessageDialog(this, erro.getMessage());
                }    
                break;  
                                               
            case "Raiz":
                try{
                    Numero_01 = Double.parseDouble(Txt_Lcd.getText());             
                    //#Copular o Objeto
                    kelps.setNumero_01(Numero_01);
                    //#Publicando no txt Area
                    saida = "";                                                                            
                    saida += kelps.OpRaizQuadrada(Numero_01);       
                    Txt_Lcd.setText(saida);
                    EnviaInfo();
                }
                catch(Exception erro){
                    JOptionPane.showMessageDialog(this, erro.getMessage());
                } 
                break;
            
            case "Potencializar":
                Numero_02 = Double.parseDouble(Txt_Lcd.getText());             
                //#Copular o Objeto
                kelps.setNumero_02(Numero_02);
                //#Publicando no txt Area
                saida = "";
                saida += kelps.OpPontecializar();
                Txt_Lcd.setText(saida);
                EnviaInfo();
                break;    

            case "Radiar":
                try{               
                    Numero_02 = Double.parseDouble(Txt_Lcd.getText());             
                    //#Copular o Objeto
                    kelps.setNumero_02(Numero_02);
                    //#Publicando no txt Area
                    saida = "";
                    saida += kelps.OpRadiar(Numero_01);
                    Txt_Lcd.setText(saida);
                    EnviaInfo();
                    break;
                }                
                catch(Exception erro){
                    JOptionPane.showMessageDialog(this, erro.getMessage());
                } 
               
        }                              
    }//GEN-LAST:event_Bt_Op_IgualActionPerformed

    private void Txt_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SairActionPerformed

    }//GEN-LAST:event_Txt_SairActionPerformed

    private void Txt_Bt_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Bt_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Txt_Bt_SairActionPerformed

    private void Txt_Bt_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Bt_SobreActionPerformed
        FrontEndCode_View2 fa = new FrontEndCode_View2(); 
        fa.setVisible(true);
    }//GEN-LAST:event_Txt_Bt_SobreActionPerformed

    private void Txt_Bt_Tela_OpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Bt_Tela_OpActionPerformed
        if (enviatexto == null){
            enviatexto = new FrontEndCode_View3();
            enviatexto.setVisible(true);                               
        }
    
        else{
            enviatexto.setVisible(true);
            enviatexto.setState(FrontEndCode_View3.NORMAL);
            }
    }//GEN-LAST:event_Txt_Bt_Tela_OpActionPerformed

    private void Bt_Op_PotencializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Op_PotencializarActionPerformed
        Numero_01 = Double.parseDouble(Txt_Lcd.getText());               
        //#Copular o Objeto
        kelps.setNumero_01(Numero_01);
        //#Publicando no txt Area
        Txt_Lcd.setText("");        
        Operaçao = "Potencializar"; 
        Level_Op ++;
    }//GEN-LAST:event_Bt_Op_PotencializarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontEndCode_View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontEndCode_View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontEndCode_View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontEndCode_View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontEndCode_View1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_DG_00;
    private javax.swing.JButton Bt_DG_01;
    private javax.swing.JButton Bt_DG_02;
    private javax.swing.JButton Bt_DG_03;
    private javax.swing.JButton Bt_DG_04;
    private javax.swing.JButton Bt_DG_05;
    private javax.swing.JButton Bt_DG_06;
    private javax.swing.JButton Bt_DG_07;
    private javax.swing.JButton Bt_DG_08;
    private javax.swing.JButton Bt_DG_09;
    private javax.swing.JButton Bt_DG_CE;
    private javax.swing.JButton Bt_DG_OnOff;
    private javax.swing.JButton Bt_DG_Ponto;
    private javax.swing.JButton Bt_Op_Divisao;
    private javax.swing.JButton Bt_Op_Igual;
    private javax.swing.JButton Bt_Op_Multiplicacao;
    private javax.swing.JButton Bt_Op_Porcentagem;
    private javax.swing.JButton Bt_Op_Potencializar;
    private javax.swing.JButton Bt_Op_Raiz_Quadrada;
    private javax.swing.JButton Bt_Op_Soma;
    private javax.swing.JButton Bt_Op_Subtracao;
    private javax.swing.JRadioButtonMenuItem Txt_Bt_Sair;
    private javax.swing.JRadioButtonMenuItem Txt_Bt_Sobre;
    private javax.swing.JRadioButtonMenuItem Txt_Bt_Tela_Op;
    private javax.swing.JTextField Txt_Lcd;
    private javax.swing.JMenu Txt_Op;
    private javax.swing.JMenu Txt_Sair;
    private javax.swing.JMenu Txt_Sobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
